CREATE\1 INDEX IF NOT EXISTS agencies_name_imo_unique ON public.agencies USING btree (name, imo_id);
CREATE\1 INDEX IF NOT EXISTS idx_agencies_imo_id ON public.agencies USING btree (imo_id);
CREATE\1 INDEX IF NOT EXISTS idx_acs_agent_id ON public.agent_carrier_states USING btree (agent_id);
CREATE\1 INDEX IF NOT EXISTS idx_acs_carrier_id ON public.agent_carrier_states USING btree (carrier_id);
CREATE\1 INDEX IF NOT EXISTS idx_acs_state_code ON public.agent_carrier_states USING btree (state_code);
CREATE\1 INDEX IF NOT EXISTS idx_agent_carriers_agent_id ON public.agent_carriers USING btree (agent_id);
CREATE\1 INDEX IF NOT EXISTS idx_agent_carriers_carrier_id ON public.agent_carriers USING btree (carrier_id);
CREATE\1 INDEX IF NOT EXISTS idx_agent_states_agent_id ON public.agent_states USING btree (agent_id);
CREATE\1 INDEX IF NOT EXISTS idx_agent_states_state_code ON public.agent_states USING btree (state_code);
CREATE\1 INDEX IF NOT EXISTS idx_agents_agency_id ON public.agents USING btree (agency_id);
CREATE\1 INDEX IF NOT EXISTS idx_agents_language ON public.agents USING btree (language);
CREATE\1 INDEX IF NOT EXISTS idx_agents_status ON public.agents USING btree (status);
CREATE\1 INDEX IF NOT EXISTS idx_agents_upline_id ON public.agents USING btree (upline_id);
CREATE\1 INDEX IF NOT EXISTS idx_agents_user_id ON public.agents USING btree (user_id);
CREATE\1 INDEX IF NOT EXISTS call_centers_name_key ON public.call_centers USING btree (name);
CREATE\1 INDEX IF NOT EXISTS idx_call_centers_country ON public.call_centers USING btree (country);
CREATE\1 INDEX IF NOT EXISTS call_result_reason_templates_status_reason_key ON public.call_result_reason_templates USING btree (status, reason);
CREATE\1 INDEX IF NOT EXISTS idx_call_result_reason_templates_active ON public.call_result_reason_templates USING btree (is_active);
CREATE\1 INDEX IF NOT EXISTS idx_call_result_reason_templates_status ON public.call_result_reason_templates USING btree (status);
CREATE\1 INDEX IF NOT EXISTS idx_call_results_lead_id ON public.call_results USING btree (lead_id);
CREATE\1 INDEX IF NOT EXISTS idx_call_results_submission_id ON public.call_results USING btree (submission_id);
CREATE\1 INDEX IF NOT EXISTS idx_call_results_user_id ON public.call_results USING btree (user_id);
CREATE\1 INDEX IF NOT EXISTS idx_callback_requests_lead_vendor ON public.callback_requests USING btree (lead_vendor);
CREATE\1 INDEX IF NOT EXISTS idx_callback_requests_requested_at ON public.callback_requests USING btree (requested_at DESC);
CREATE\1 INDEX IF NOT EXISTS idx_callback_requests_status ON public.callback_requests USING btree (status);
CREATE\1 INDEX IF NOT EXISTS idx_callback_requests_submission_id ON public.callback_requests USING btree (submission_id);
CREATE\1 INDEX IF NOT EXISTS idx_carrier_info_carrier_id ON public.carrier_info USING btree (carrier_id);
CREATE\1 INDEX IF NOT EXISTS idx_carrier_info_group_type ON public.carrier_info USING btree (group_type);
CREATE\1 INDEX IF NOT EXISTS idx_carrier_products_carrier_id ON public.carrier_products USING btree (carrier_id);
CREATE\1 INDEX IF NOT EXISTS idx_carrier_products_product_id ON public.carrier_products USING btree (product_id);
CREATE\1 INDEX IF NOT EXISTS carriers_name_key ON public.carriers USING btree (name);
CREATE\1 INDEX IF NOT EXISTS center_thresholds_center_name_key ON public.center_thresholds USING btree (center_name);
CREATE\1 INDEX IF NOT EXISTS center_thresholds_lead_vendor_key ON public.center_thresholds USING btree (lead_vendor);
CREATE\1 INDEX IF NOT EXISTS idx_center_thresholds_lead_vendor ON public.center_thresholds USING btree (lead_vendor);
CREATE\1 INDEX IF NOT EXISTS idx_center_thresholds_tier ON public.center_thresholds USING btree (tier);
CREATE\1 INDEX IF NOT EXISTS idx_commissions_paid_at ON public.commissions USING btree (paid_at);
CREATE\1 INDEX IF NOT EXISTS idx_commissions_policy_number ON public.commissions USING btree (policy_number);
CREATE\1 INDEX IF NOT EXISTS idx_commissions_status ON public.commissions USING btree (status);
CREATE\1 INDEX IF NOT EXISTS daily_deal_flow_submission_id_date_key ON public.daily_deal_flow USING btree (submission_id, date);
CREATE\1 INDEX IF NOT EXISTS idx_daily_deal_flow_agent ON public.daily_deal_flow USING btree (agent);
CREATE\1 INDEX IF NOT EXISTS idx_daily_deal_flow_call_center_id ON public.daily_deal_flow USING btree (call_center_id);
CREATE\1 INDEX IF NOT EXISTS idx_daily_deal_flow_date ON public.daily_deal_flow USING btree (date);
CREATE\1 INDEX IF NOT EXISTS idx_daily_deal_flow_ghl_location_id ON public.daily_deal_flow USING btree (ghl_location_id);
CREATE\1 INDEX IF NOT EXISTS idx_daily_deal_flow_ghl_opportunity_id ON public.daily_deal_flow USING btree (ghl_opportunity_id);
CREATE\1 INDEX IF NOT EXISTS idx_daily_deal_flow_status ON public.daily_deal_flow USING btree (status);
CREATE\1 INDEX IF NOT EXISTS idx_daily_deal_flow_submission_id ON public.daily_deal_flow USING btree (submission_id);
CREATE\1 INDEX IF NOT EXISTS departments_publisher_manager_user_id_idx ON public.departments USING btree (publisher_manager_user_id);
CREATE\1 INDEX IF NOT EXISTS idx_disposition_events_lead ON public.disposition_events USING btree (lead_id);
CREATE\1 INDEX IF NOT EXISTS idx_disposition_events_submission ON public.disposition_events USING btree (submission_id);
CREATE\1 INDEX IF NOT EXISTS disposition_flow_nodes_flow_id_node_key_key ON public.disposition_flow_nodes USING btree (flow_id, node_key);
CREATE\1 INDEX IF NOT EXISTS idx_disposition_flow_nodes_flow ON public.disposition_flow_nodes USING btree (flow_id);
CREATE\1 INDEX IF NOT EXISTS disposition_flow_options_node_id_option_key_key ON public.disposition_flow_options USING btree (node_id, option_key);
CREATE\1 INDEX IF NOT EXISTS disposition_flows_flow_key_key ON public.disposition_flows USING btree (flow_key);
CREATE\1 INDEX IF NOT EXISTS disposition_flows_pipeline_stage_name_flow_key_key ON public.disposition_flows USING btree (pipeline_stage_name, flow_key);
CREATE\1 INDEX IF NOT EXISTS idx_disposition_flows_stage ON public.disposition_flows USING btree (pipeline_stage_name) WHERE (is_active = true);
CREATE\1 INDEX IF NOT EXISTS imos_name_key ON public.imos USING btree (name);
CREATE\1 INDEX IF NOT EXISTS lead_notes_deal_tracker_review_note_id_key ON public.lead_notes USING btree (deal_tracker_review_note_id);
CREATE\1 INDEX IF NOT EXISTS lead_notes_lead_id_created_at_idx ON public.lead_notes USING btree (lead_id, created_at DESC);
CREATE\1 INDEX IF NOT EXISTS idx_lqe_queue_created ON public.lead_queue_events USING btree (queue_item_id, created_at DESC);
CREATE\1 INDEX IF NOT EXISTS idx_lqi_assigned_ba ON public.lead_queue_items USING btree (assigned_ba_id) WHERE (status = 'active'::queue_status_enum);
CREATE\1 INDEX IF NOT EXISTS idx_lqi_assigned_la ON public.lead_queue_items USING btree (assigned_la_id) WHERE (status = 'active'::queue_status_enum);
CREATE\1 INDEX IF NOT EXISTS idx_lqi_call_center ON public.lead_queue_items USING btree (call_center_id, status);
CREATE\1 INDEX IF NOT EXISTS idx_lqi_created_at ON public.lead_queue_items USING btree (created_at DESC);
CREATE\1 INDEX IF NOT EXISTS idx_lqi_owner ON public.lead_queue_items USING btree (current_owner_user_id) WHERE (status = 'active'::queue_status_enum);
CREATE\1 INDEX IF NOT EXISTS idx_lqi_queue_type_status ON public.lead_queue_items USING btree (queue_type, status);
CREATE\1 INDEX IF NOT EXISTS uq_lead_queue_active_submission ON public.lead_queue_items USING btree (submission_id) WHERE ((status = 'active'::queue_status_enum) AND (submission_id IS NOT NULL));
CREATE\1 INDEX IF NOT EXISTS leads_call_center_id_idx ON public.leads USING btree (call_center_id);
CREATE\1 INDEX IF NOT EXISTS leads_created_at_idx ON public.leads USING btree (created_at DESC);
CREATE\1 INDEX IF NOT EXISTS leads_lead_unique_id_unique_idx ON public.leads USING btree (lead_unique_id);
CREATE\1 INDEX IF NOT EXISTS leads_pipeline_id_idx ON public.leads USING btree (pipeline_id);
CREATE\1 INDEX IF NOT EXISTS leads_policy_id_key ON public.leads USING btree (policy_id) WHERE (policy_id IS NOT NULL);
CREATE\1 INDEX IF NOT EXISTS leads_stage_id_idx ON public.leads USING btree (stage_id);
CREATE\1 INDEX IF NOT EXISTS leads_submission_id_key ON public.leads USING btree (submission_id);
CREATE\1 INDEX IF NOT EXISTS leads_submitted_by_idx ON public.leads USING btree (submitted_by);
CREATE\1 INDEX IF NOT EXISTS leads_sync_required_idx ON public.leads USING btree (sync_required);
CREATE\1 INDEX IF NOT EXISTS idx_permissions_resource_action ON public.permissions USING btree (resource, action);
CREATE\1 INDEX IF NOT EXISTS permissions_key_key ON public.permissions USING btree (key);
CREATE\1 INDEX IF NOT EXISTS pipeline_stages_pipeline_id_name_key ON public.pipeline_stages USING btree (pipeline_id, name);
CREATE\1 INDEX IF NOT EXISTS pipeline_stages_pipeline_id_position_key ON public.pipeline_stages USING btree (pipeline_id, "position");
CREATE\1 INDEX IF NOT EXISTS pipelines_name_key ON public.pipelines USING btree (name);
CREATE\1 INDEX IF NOT EXISTS idx_policies_callback_datetime ON public.policies USING btree (callback_datetime);
CREATE\1 INDEX IF NOT EXISTS idx_policies_disposition ON public.policies USING btree (disposition);
CREATE\1 INDEX IF NOT EXISTS idx_policies_disposition_date ON public.policies USING btree (disposition_date);
CREATE\1 INDEX IF NOT EXISTS idx_policies_is_active ON public.policies USING btree (is_active) WHERE (is_active = true);
CREATE\1 INDEX IF NOT EXISTS idx_policies_lead_id ON public.policies USING btree (lead_id);
CREATE\1 INDEX IF NOT EXISTS policies_monday_item_id_key ON public.policies USING btree (monday_item_id);
CREATE\1 INDEX IF NOT EXISTS policies_policy_number_key ON public.policies USING btree (policy_number);
CREATE\1 INDEX IF NOT EXISTS idx_product_guides_category ON public.product_guides USING btree (category);
CREATE\1 INDEX IF NOT EXISTS idx_product_guides_display_order ON public.product_guides USING btree (display_order);
CREATE\1 INDEX IF NOT EXISTS idx_product_guides_slug ON public.product_guides USING btree (slug);
CREATE\1 INDEX IF NOT EXISTS product_guides_slug_key ON public.product_guides USING btree (slug);
CREATE\1 INDEX IF NOT EXISTS products_name_key ON public.products USING btree (name);
CREATE\1 INDEX IF NOT EXISTS idx_role_permissions_permission_id ON public.role_permissions USING btree (permission_id);
CREATE\1 INDEX IF NOT EXISTS idx_role_permissions_role_id ON public.role_permissions USING btree (role_id);
CREATE\1 INDEX IF NOT EXISTS roles_key_key ON public.roles USING btree (key);
CREATE\1 INDEX IF NOT EXISTS ssn_duplicate_stage_rules_stage_name_key ON public.ssn_duplicate_stage_rules USING btree (stage_name);
CREATE\1 INDEX IF NOT EXISTS stage_disposition_map_disposition_key ON public.stage_disposition_map USING btree (disposition);
CREATE\1 INDEX IF NOT EXISTS stage_disposition_map_stage_id_key ON public.stage_disposition_map USING btree (stage_id);
CREATE\1 INDEX IF NOT EXISTS states_name_key ON public.states USING btree (name);
CREATE\1 INDEX IF NOT EXISTS ticket_comments_ticket_id_created_at_idx ON public.ticket_comments USING btree (ticket_id, created_at DESC);
CREATE\1 INDEX IF NOT EXISTS ticket_followers_user_id_idx ON public.ticket_followers USING btree (user_id);
CREATE\1 INDEX IF NOT EXISTS ticket_routing_rules_active_priority_idx ON public.ticket_routing_rules USING btree (is_active, priority);
CREATE\1 INDEX IF NOT EXISTS tickets_assignee_id_idx ON public.tickets USING btree (assignee_id);
CREATE\1 INDEX IF NOT EXISTS tickets_call_center_id_idx ON public.tickets USING btree (call_center_id);
CREATE\1 INDEX IF NOT EXISTS tickets_lead_id_idx ON public.tickets USING btree (lead_id);
CREATE\1 INDEX IF NOT EXISTS tickets_publisher_id_idx ON public.tickets USING btree (publisher_id);
CREATE\1 INDEX IF NOT EXISTS tickets_status_idx ON public.tickets USING btree (status);
CREATE\1 INDEX IF NOT EXISTS idx_ucs_carrier_id ON public.upline_carrier_states USING btree (carrier_id);
CREATE\1 INDEX IF NOT EXISTS idx_ucs_state_code ON public.upline_carrier_states USING btree (state_code);
CREATE\1 INDEX IF NOT EXISTS user_creation_audit_created_at_idx ON public.user_creation_audit USING btree (created_at DESC);
CREATE\1 INDEX IF NOT EXISTS idx_user_permissions_permission_id ON public.user_permissions USING btree (permission_id);
CREATE\1 INDEX IF NOT EXISTS idx_user_permissions_user_id ON public.user_permissions USING btree (user_id);
CREATE\1 INDEX IF NOT EXISTS idx_users_call_center ON public.users USING btree (call_center_id);
CREATE\1 INDEX IF NOT EXISTS idx_users_department_id ON public.users USING btree (department_id);
CREATE\1 INDEX IF NOT EXISTS idx_users_role_id ON public.users USING btree (role_id);
CREATE\1 INDEX IF NOT EXISTS idx_users_status ON public.users USING btree (status);
CREATE\1 INDEX IF NOT EXISTS idx_verification_items_field_name ON public.verification_items USING btree (field_name);
CREATE\1 INDEX IF NOT EXISTS idx_verification_items_is_verified ON public.verification_items USING btree (is_verified);
CREATE\1 INDEX IF NOT EXISTS idx_verification_items_session_id ON public.verification_items USING btree (session_id);
CREATE\1 INDEX IF NOT EXISTS verification_items_session_id_field_name_key ON public.verification_items USING btree (session_id, field_name);
CREATE\1 INDEX IF NOT EXISTS idx_verification_sessions_buffer_agent ON public.verification_sessions USING btree (buffer_agent_id);
CREATE\1 INDEX IF NOT EXISTS idx_verification_sessions_claimed_at ON public.verification_sessions USING btree (claimed_at);
CREATE\1 INDEX IF NOT EXISTS idx_verification_sessions_licensed_agent ON public.verification_sessions USING btree (licensed_agent_id);
CREATE\1 INDEX IF NOT EXISTS idx_verification_sessions_status ON public.verification_sessions USING btree (status);
CREATE\1 INDEX IF NOT EXISTS idx_verification_sessions_submission_id ON public.verification_sessions USING btree (submission_id);
CREATE\1 INDEX IF NOT EXISTS verification_sessions_submission_id_key ON public.verification_sessions USING btree (submission_id);